In [2]:
## Import necessary modules
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.dates import AutoDateFormatter, AutoDateLocator, WeekdayLocator, MonthLocator, DateFormatter
from matplotlib.dates import MO, TU, WE, TH, FR, SA, SU
from matplotlib.ticker import AutoMinorLocator
import numpy as np
import datetime, calendar
%matplotlib tk


## Import data frome pickle generated from hotline_daily.py
data = pd.read_pickle('pickle_hotline_0904.pkl')

In [3]:
def rearrange(df):
    index_filter=df.loc[['tix']] ## select all hours-index rows
    
    hourse=list(range(0,25))  ## these is from 0 to 24 (25 entries!) and maps the hour indices
    mh=index_filter[hourse]  ## columns with half- and hour steps were named 0-24
    oldcols=mh.columns.values.tolist() ## list of the names of the hourse
    newcols=mh.loc['tix'].drop_duplicates().loc['tix'].values.tolist() ## one row of the hour indices provides the new column names
    cols=dict(zip(oldcols,newcols)) ## old column names get mapped to new columns names

    mhnew=df.rename(columns=cols).drop('tix') ## new dataframe has the old 'tix' entries as column names; 'tix' rows are dropped since not needed any more
    mhnew=mhnew.reset_index().set_index(['xlday']).rename(columns={'index':'status'}) ## new index will be the excel date numbers, old index is moved to a column named 'status'
    
    return mhnew

In [4]:
def timerange(*,df, years, months=range(1,13), weeks=range(1,53), weekdays=['Mon','Tue','Wed','Thu','Fri','Sat','Sun']):
    resultat=df.loc[(df['year'].isin(years)) & (df['month'].isin(months)) & (df['weekday'].isin(weekdays))]
    return resultat

# end of function definitions

In [5]:
ndata=rearrange(data)
#ndata.head()

### time range filter:
Arguments must be passed as a list or as a range. Example:

**timerange(df=ndata,years=[2016,2017],months=[3],weeks=[6],weekdays=['Sun','Sun'])**

Note the double entry for a single weekday!
Leaving parameters empty gives default values (=all). Months and Weeks may be mutually exclusive and raise exceptions

In [6]:
plotframe = timerange(df=ndata,years=[2017],months=[3])

In [7]:
plotframe

,status,month,year,00:00-00:30,00:30-01:30,01:30-02:30,02:30-03:30,03:30-04:30,04:30-05:30,05:30-06:30,...,19:30-20:30,20:30-21:30,21:30-22:30,22:30-23:30,23:30-00:00,summa,day,date,week,weekday
xlday,,,,,,,,,,,,,,,,,,,,,
42795.0,angekommen,3,2017,0,0,0,0,0,0,0,...,1,1,0,1,0,38,1,2017-03-01,9,Wed
42795.0,verbunden,3,2017,0,0,0,0,0,0,0,...,1,0,0,0,0,26,1,2017-03-01,9,Wed
42795.0,verloren,3,2017,0,0,0,0,0,0,0,...,0,1,0,1,0,12,1,2017-03-01,9,Wed
42795.0,servicelevel,3,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1,0,NaN,0,NaN,0.684211,1,2017-03-01,9,Wed
42796.0,angekommen,3,2017,0,0,0,0,0,0,0,...,1,1,0,0,0,76,2,2017-03-02,9,Thu
42796.0,verbunden,3,2017,0,0,0,0,0,0,0,...,1,1,0,0,0,59,2,2017-03-02,9,Thu
42796.0,verloren,3,2017,0,0,0,0,0,0,0,...,0,0,0,0,0,17,2,2017-03-02,9,Thu
42796.0,servicelevel,3,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1,1,NaN,NaN,NaN,0.776316,2,2017-03-02,9,Thu
42797.0,angekommen,3,2017,0,0,0,0,0,0,0,...,0,1,0,0,0,44,3,2017-03-03,9,Fri
42797.0,verbunden,3,2017,0,0,0,0,0,0,0,...,0,1,0,0,0,37,3,2017-03-03,9,Fri
42797.0,verloren,3,2017,0,0,0,0,0,0,0,...,0,0,0,0,0,7,3,2017-03-03,9,Fri
42797.0,servicelevel,3,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1,NaN,NaN,NaN,0.840909,3,2017-03-03,9,Fri
42798.0,angekommen,3,2017,0,0,0,0,0,0,0,...,0,0,4,0,0,24,4,2017-03-04,9,Sat
42798.0,verbunden,3,2017,0,0,0,0,0,0,0,...,0,0,4,0,0,19,4,2017-03-04,9,Sat
42798.0,verloren,3,2017,0,0,0,0,0,0,0,...,0,0,0,0,0,5,4,2017-03-04,9,Sat
42798.0,servicelevel,3,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1,NaN,NaN,0.791667,4,2017-03-04,9,Sat
42799.0,angekommen,3,2017,0,0,0,0,0,0,0,...,0,1,0,0,0,6,5,2017-03-05,9,Sun
42799.0,verbunden,3,2017,0,0,0,0,0,0,0,...,0,1,0,0,0,3,5,2017-03-05,9,Sun
42799.0,verloren,3,2017,0,0,0,0,0,0,0,...,0,0,0,0,0,3,5,2017-03-05,9,Sun
42799.0,servicelevel,3,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1,NaN,NaN,NaN,0.5,5,2017-03-05,9,Sun
42800.0,angekommen,3,2017,0,0,0,0,0,0,0,...,1,0,0,0,0,56,6,2017-03-06,10,Mon
42800.0,verbunden,3,2017,0,0,0,0,0,0,0,...,0,0,0,0,0,31,6,2017-03-06,10,Mon
42800.0,verloren,3,2017,0,0,0,0,0,0,0,...,1,0,0,0,0,25,6,2017-03-06,10,Mon
42800.0,servicelevel,3,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,NaN,NaN,NaN,NaN,0.553571,6,2017-03-06,10,Mon
42801.0,angekommen,3,2017,0,0,0,0,0,0,0,...,3,1,0,0,0,25,7,2017-03-07,10,Tue
42801.0,verbunden,3,2017,0,0,0,0,0,0,0,...,3,1,0,0,0,21,7,2017-03-07,10,Tue
42801.0,verloren,3,2017,0,0,0,0,0,0,0,...,0,0,0,0,0,4,7,2017-03-07,10,Tue
42801.0,servicelevel,3,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1,1,NaN,NaN,NaN,0.84,7,2017-03-07,10,Tue
42802.0,angekommen,3,2017,0,0,0,0,0,0,0,...,0,0,0,0,0,53,8,2017-03-08,10,Wed
42802.0,verbunden,3,2017,0,0,0,0,0,0,0,...,0,0,0,0,0,44,8,2017-03-08,10,Wed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42818.0,verloren,3,2017,0,0,0,0,0,0,0,...,0,0,0,0,0,5,24,2017-03-24,12,Fri
42818.0,servicelevel,3,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1,NaN,NaN,NaN,NaN,0.9,24,2017-03-24,12,Fri
42819.0,angekommen,3,2017,0,0,0,1,0,0,0,...,1,0,0,0,0,24,25,2017-03-25,12,Sat
42819.0,verbunden,3,2017,0,0,0,1,0,0,0,...,1,0,0,0,0,19,25,2017-03-25,12,Sat
42819.0,verloren,3,2017,0,0,0,0,0,0,0,...,0,0,0,0,0,5,25,2017-03-25,12,Sat
42819.0,servicelevel,3,2017,NaN,NaN,NaN,1,NaN,NaN,NaN,...,1,NaN,NaN,NaN,NaN,0.791667,25,2017-03-25,12,Sat
42820.0,angekommen,3,2017,0,0,0,0,0,0,0,...,0,0,0,0,0,3,26,2017-03-26,12,Sun
42820.0,verbunden,3,2017,0,0,0,0,0,0,0,...,0,0,0,0,0,1,26,2017-03-26,12,Sun
42820.0,verloren,3,2017,0,0,0,0,0,0,0,...,0,0,0,0,0,2,26,2017-03-26,12,Sun
42820.0,servicelevel,3,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.333333,26,2017-03-26,12,Sun
42821.0,angekommen,3,2017,0,0,0,0,0,0,0,...,3,0,1,0,0,32,27,2017-03-27,13,Mon
42821.0,verbunden,3,2017,0,0,0,0,0,0,0,...,1,0,1,0,0,26,27,2017-03-27,13,Mon
42821.0,verloren,3,2017,0,0,0,0,0,0,0,...,2,0,0,0,0,6,27,2017-03-27,13,Mon
42821.0,servicelevel,3,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.333333,NaN,1,NaN,NaN,0.8125,27,2017-03-27,13,Mon
42822.0,angekommen,3,2017,0,0,0,0,0,0,0,...,2,1,0,1,0,65,28,2017-03-28,13,Tue
42822.0,verbunden,3,2017,0,0,0,0,0,0,0,...,2,1,0,0,0,61,28,2017-03-28,13,Tue
42822.0,verloren,3,2017,0,0,0,0,0,0,0,...,0,0,0,1,0,4,28,2017-03-28,13,Tue
42822.0,servicelevel,3,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1,1,NaN,0,NaN,0.938462,28,2017-03-28,13,Tue
42823.0,angekommen,3,2017,0,0,0,0,0,0,0,...,1,3,0,0,0,44,29,2017-03-29,13,Wed
42823.0,verbunden,3,2017,0,0,0,0,0,0,0,...,1,2,0,0,0,38,29,2017-03-29,13,Wed
42823.0,verloren,3,2017,0,0,0,0,0,0,0,...,0,1,0,0,0,6,29,2017-03-29,13,Wed
42823.0,servicelevel,3,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1,0.666667,NaN,NaN,NaN,0.863636,29,2017-03-29,13,Wed
42824.0,angekommen,3,2017,0,0,0,0,0,0,0,...,5,0,0,0,0,49,30,2017-03-30,13,Thu
42824.0,verbunden,3,2017,0,0,0,0,0,0,0,...,5,0,0,0,0,45,30,2017-03-30,13,Thu
42824.0,verloren,3,2017,0,0,0,0,0,0,0,...,0,0,0,0,0,4,30,2017-03-30,13,Thu
42824.0,servicelevel,3,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1,NaN,NaN,NaN,NaN,0.918367,30,2017-03-30,13,Thu
42825.0,angekommen,3,2017,0,0,0,0,0,0,0,...,1,1,0,0,0,31,31,2017-03-31,13,Fri
42825.0,verbunden,3,2017,0,0,0,0,0,0,0,...,1,0,0,0,0,29,31,2017-03-31,13,Fri
42825.0,verloren,3,2017,0,0,0,0,0,0,0,...,0,1,0,0,0,2,31,2017-03-31,13,Fri
42825.0,servicelevel,3,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1,0,NaN,NaN,NaN,0.935484,31,2017-03-31,13,Fri