In [10]:
## Import necessary modules
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.dates import date2num, AutoDateFormatter, AutoDateLocator, WeekdayLocator, MonthLocator, DayLocator, DateLocator, DateFormatter
from matplotlib.dates import MO, TU, WE, TH, FR, SA, SU
from matplotlib.ticker import AutoMinorLocator
import numpy as np
import datetime, calendar
from datetime import timedelta
import matplotlib.patches as mpatches
%matplotlib tk

data = pd.read_pickle('/home/keuch/gits/keuch/code_box/pyt/spreadsheetparsing/entwuerfe/xls_testruns/doe_pickle_1458.pkl') # this one for average times

In [11]:
print(data.columns)

Index(['tm', 'dt', 'yy', 'mm', 'ww', 'wd', 'dd', 'xl', 'hh', 'an', 'vb', 'vl',
       'ht', 'tt', 'acw', 'bz', 'dectt', 'decht', 'decacw'],
      dtype='object')

In [12]:
# functions that will be apllied on grouping, left out dt bz and hh; dt and bz should be indices, hh can be dropped
colfunx_collapse_dt={'yy':'first', 'mm':'first', 'ww':'first', 'wd':'first', 'dd':'first', 'xl':'first', 'an':'sum', 'vb':'sum', 'vl':'sum', 'ht':'sum', 'tt':'sum', 'acw':'sum','decht':'sum', 'dectt':'sum', 'decacw':'sum'}
# group data by day and bearbzeit
data_grouped=data.groupby(['dt','bz']).agg(colfunx_collapse_dt)

In [13]:
# dates without neben- or kernzeit should contain each index, but fill them with null. Solution see https://stackoverflow.com/questions/17287933/filling-in-date-gaps-in-multiindex-pandas-dataframe
dg=data_grouped.unstack('dt').fillna(0).stack('dt')
dg2=dg.reorder_levels(['dt','bz'])

In [14]:
# averages as their own columns
dg2['aht']=(dg2['ht']/dg2['vb']).fillna(0)
dg2['att']=(dg2['tt']/dg2['vb']).fillna(0)
dg2['aacw']=(dg2['acw']/dg2['vb']).fillna(0)

# function for conversion of excel-floats to timedelta objects
def float_to_delta(xlfloat):
    deltatime=timedelta(xlfloat)
    return deltatime
dg2[['td_att','td_aht','td_aacw']] = dg2[['att', 'aht', 'aacw']].applymap(float_to_delta)

# reorder columns for better comprehensibility, left out the decimal times and the excel-averages
col_order=['xl','yy','mm','dd','ww','wd','an','vb','vl','ht','tt','acw','td_aht','td_att','td_aacw']
dg2=dg2[col_order]

In [15]:
kernzeit=dg2.xs('k', level=1, drop_level=False)
nebnzeit=dg2.xs('n', level=1, drop_level=False)
# both frames share the same index (level 0, i.e. datetime.date)

In [16]:
kernzeit.tail()
#kernzeit.replace(0, np.nan)

,,xl,yy,mm,dd,ww,wd,an,vb,vl,ht,tt,acw,td_aht,td_att,td_aacw
dt,bz,,,,,,,,,,,,,,,
2017-10-04,k,43012.0,2017.0,10.0,4.0,40.0,Wed,326.0,268.0,58.0,0.726447,0.600822,0.125625,00:03:54.197761,00:03:13.697761,00:00:40.500000
2017-10-05,k,43013.0,2017.0,10.0,5.0,40.0,Thu,303.0,257.0,46.0,0.739329,0.627847,0.111481,00:04:08.552529,00:03:31.073930,00:00:37.478599
2017-10-06,k,43014.0,2017.0,10.0,6.0,40.0,Fri,371.0,332.0,39.0,0.971354,0.815104,0.156250,00:04:12.786145,00:03:32.123494,00:00:40.662651
2017-10-07,k,43015.0,2017.0,10.0,7.0,40.0,Sat,66.0,50.0,16.0,0.167535,0.140706,0.026829,00:04:49.500000,00:04:03.140000,00:00:46.360000
2017-10-08,k,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.000000,0.000000,0.000000,00:00:00,00:00:00,00:00:00

In [17]:
XAchse=kernzeit.index.levels[0]
YAchse=kernzeit['td_aht']

In [18]:
#ax=plt.subplot(111)
#ax.plot(kernzeit.index.levels[0],,ls='-',color='red')

In [19]:
colfunx_collapse_dt2={'yy':'first', 'mm':'first', 'wd':'first', 'dd':'first', 'xl':'first', 'an':'sum', 'vb':'sum', 'vl':'sum', 'ht':'sum', 'tt':'sum', 'acw':'sum','decht':'sum', 'dectt':'sum', 'decacw':'sum'}
data_grouped_byweek=data_grouped=data.groupby(['dt','bz','ww']).agg(colfunx_collapse_dt2)

In [20]:
def get_year(dtobject):
    jahr=dtobject.year
    return jahr

In [26]:
colfunx_collapse_dt2={'date_dt':'first','yy':'first', 'mm':'first', 'an':'sum', 'vb':'sum', 'vl':'sum', 'ht':'sum', 'tt':'sum', 'acw':'sum'}
col_order2=['yy','mm','an','vb','vl','ht','tt','acw']
data['date_dt']=data.index
dg3=data.groupby(['ww','bz']).agg(colfunx_collapse_dt2)
dg4=dg3.unstack('bz').fillna(0).stack('bz')
dg5=dg4.reorder_levels(['ww','bz'])
#print(data.date_dt)



dg5['yy'] = dg5['date_dt'].apply(get_year)

dg5ordered=dg5[col_order2]
dg3.tail()

        vb        ht       acw   an   vl    date_dt    yy        tt  mm
ww bz
48 k   573  2.297581  1.005579  628   55 2016-11-28  2016  1.292002  11
49 k   777  3.033553  1.319618  877  100 2016-12-05  2016  1.713935  12
50 k   832  3.266319  1.193241  954  122 2016-12-12  2016  2.073079  12
51 k   755  2.289456  0.571134  860  105 2016-12-19  2016  1.718322  12
52 k   280  0.873310  0.200278  335   55 2016-12-26  2016  0.673032  12

In [65]:
dg3.loc[[40,'bz'=='k']]

         vb        ht       acw    an   vl             date_dt    yy  \
ww bz
40 k   1058  3.041470  0.486111  1221  163 2017-10-02 08:00:00  2017
   n     45  0.049132  0.013681    55   10 2017-10-02 00:00:00  2017

             tt  mm
ww bz
40 k   2.555359  10
   n   0.035451  10

In [129]:
# functions that will be apllied on grouping, left out dt bz and hh; dt and bz should be indices, hh can be dropped
colfunx_collapse_dt={'an':'sum', 'vb':'sum', 'vl':'sum', 'ht':'sum', 'tt':'sum', 'acw':'sum'}
# group data by day and bearbzeit
data_byday=data.groupby(['dt','bz']).agg(colfunx_collapse_dt)

In [162]:
(datindex,bzindex)=data_byday.index.levels
newinex=pd.MultiIndex.from_product([datindex,bzindex])
nbyday=data_byday.reindex(newinex).fillna(0)
nbyday.index.set_names(['date','bzeit'],inplace=True)
kernzeit2=nbyday.xs('k', level=1, drop_level=True)
nebnzeit2=nbyday.xs('n', level=1, drop_level=True)

In [163]:
def get_week(dtobject):
    yr=dtobject.year
    mn=dtobject.month
    wk=dtobject.isocalendar()[1]
    return yr,mn,wk
nebnzeit2['datum']=nebnzeit2.index

/home/keuch/gits/keuch/code_box/pyt/spreadsheetparsing/entwuerfe/ve/lib/python3.4/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [166]:
#nebnzeit2['jahr'],nebnzeit2['monat'],
nebnzeit2['woche']=nebnzeit2.datum.apply(get_week)[2]

ValueError: Length of values does not match length of index

In [161]:
nebnzeit2

,vb,acw,an,tt,vl,ht,datum,jahr,monat,woche
date,,,,,,,,,,
2016-11-14,0.0,0.000000,0.0,0.000000,0.0,0.000000,2016-11-14,Ä,g,h
2016-11-15,0.0,0.000000,0.0,0.000000,0.0,0.000000,2016-11-15,Ä,g,h
2016-11-16,0.0,0.000000,0.0,0.000000,0.0,0.000000,2016-11-16,Ä,g,h
2016-11-17,0.0,0.000000,0.0,0.000000,0.0,0.000000,2016-11-17,Ä,g,h
2016-11-18,0.0,0.000000,0.0,0.000000,0.0,0.000000,2016-11-18,Ä,g,h
2016-11-19,0.0,0.000000,0.0,0.000000,0.0,0.000000,2016-11-19,Ä,g,h
2016-11-20,0.0,0.000000,0.0,0.000000,0.0,0.000000,2016-11-20,Ä,g,h
2016-11-21,0.0,0.000000,0.0,0.000000,0.0,0.000000,2016-11-21,Ä,g,h
2016-11-22,0.0,0.000000,0.0,0.000000,0.0,0.000000,2016-11-22,Ä,g,h
2016-11-23,0.0,0.000000,0.0,0.000000,0.0,0.000000,2016-11-23,Ä,g,h
2016-11-24,0.0,0.000000,0.0,0.000000,0.0,0.000000,2016-11-24,Ä,g,h
2016-11-25,0.0,0.000000,0.0,0.000000,0.0,0.000000,2016-11-25,Ä,g,h
2016-11-26,0.0,0.000000,0.0,0.000000,0.0,0.000000,2016-11-26,Ä,g,h
2016-11-27,0.0,0.000000,0.0,0.000000,0.0,0.000000,2016-11-27,Ä,g,h
2016-11-28,0.0,0.000000,0.0,0.000000,0.0,0.000000,2016-11-28,Ä,g,h
2016-11-29,0.0,0.000000,0.0,0.000000,0.0,0.000000,2016-11-29,Ä,g,h
2016-11-30,0.0,0.000000,0.0,0.000000,0.0,0.000000,2016-11-30,Ä,g,h
2016-12-01,0.0,0.000000,0.0,0.000000,0.0,0.000000,2016-12-01,Ä,g,h
2016-12-02,0.0,0.000000,0.0,0.000000,0.0,0.000000,2016-12-02,Ä,g,h
2016-12-03,0.0,0.000000,0.0,0.000000,0.0,0.000000,2016-12-03,Ä,g,h
2016-12-04,0.0,0.000000,0.0,0.000000,0.0,0.000000,2016-12-04,Ä,g,h
2016-12-05,0.0,0.000000,0.0,0.000000,0.0,0.000000,2016-12-05,Ä,g,h
2016-12-06,0.0,0.000000,0.0,0.000000,0.0,0.000000,2016-12-06,Ä,g,h
2016-12-07,0.0,0.000000,0.0,0.000000,0.0,0.000000,2016-12-07,Ä,g,h
2016-12-08,0.0,0.000000,0.0,0.000000,0.0,0.000000,2016-12-08,Ä,g,h
2016-12-09,0.0,0.000000,0.0,0.000000,0.0,0.000000,2016-12-09,Ä,g,h
2016-12-10,0.0,0.000000,0.0,0.000000,0.0,0.000000,2016-12-10,Ä,g,h
2016-12-11,0.0,0.000000,0.0,0.000000,0.0,0.000000,2016-12-11,Ä,g,h
2016-12-12,0.0,0.000000,0.0,0.000000,0.0,0.000000,2016-12-12,Ä,g,h
2016-12-13,0.0,0.000000,0.0,0.000000,0.0,0.000000,2016-12-13,Ä,g,h
...,...,...,...,...,...,...,...,...,...,...
2017-09-09,14.0,0.005532,17.0,0.007188,3.0,0.012720,2017-09-09,Ä,g,h
2017-09-10,10.0,0.005012,12.0,0.002627,2.0,0.007639,2017-09-10,Ä,g,h
2017-09-11,3.0,0.000775,4.0,0.003785,1.0,0.004560,2017-09-11,Ä,g,h
2017-09-12,5.0,0.002037,5.0,0.006551,0.0,0.008588,2017-09-12,Ä,g,h
2017-09-13,3.0,0.000313,3.0,0.002604,0.0,0.002917,2017-09-13,Ä,g,h
2017-09-14,4.0,0.002593,5.0,0.002257,1.0,0.004850,2017-09-14,Ä,g,h
2017-09-15,5.0,0.002072,6.0,0.004271,1.0,0.006343,2017-09-15,Ä,g,h
2017-09-16,20.0,0.003831,25.0,0.017500,5.0,0.021331,2017-09-16,Ä,g,h
2017-09-17,6.0,0.000972,7.0,0.002720,1.0,0.003692,2017-09-17,Ä,g,h
2017-09-18,6.0,0.002905,6.0,0.007014,0.0,0.009919,2017-09-18,Ä,g,h
2017-09-19,4.0,0.000949,5.0,0.005498,1.0,0.006447,2017-09-19,Ä,g,h
2017-09-20,2.0,0.000741,2.0,0.001528,0.0,0.002269,2017-09-20,Ä,g,h
2017-09-21,1.0,0.000058,2.0,0.000382,1.0,0.000440,2017-09-21,Ä,g,h
2017-09-22,5.0,0.001227,5.0,0.002488,0.0,0.003715,2017-09-22,Ä,g,h
2017-09-23,5.0,0.001586,7.0,0.003762,2.0,0.005347,2017-09-23,Ä,g,h
2017-09-24,3.0,0.002083,3.0,0.001273,0.0,0.003356,2017-09-24,Ä,g,h
2017-09-25,1.0,0.000694,2.0,0.000810,1.0,0.001505,2017-09-25,Ä,g,h
2017-09-26,7.0,0.002917,7.0,0.009815,0.0,0.012731,2017-09-26,Ä,g,h
2017-09-27,5.0,0.001516,5.0,0.004757,0.0,0.006273,2017-09-27,Ä,g,h
2017-09-28,6.0,0.000961,6.0,0.005116,0.0,0.006076,2017-09-28,Ä,g,h
2017-09-29,4.0,0.000799,5.0,0.001308,1.0,0.002106,2017-09-29,Ä,g,h
2017-09-30,9.0,0.004491,10.0,0.007153,1.0,0.011644,2017-09-30,Ä,g,h
2017-10-01,2.0,0.000891,6.0,0.000752,4.0,0.001644,2017-10-01,Ä,g,h
2017-10-02,9.0,0.001956,9.0,0.005613,0.0,0.007569,2017-10-02,Ä,g,h
2017-10-03,0.0,0.000000,0.0,0.000000,0.0,0.000000,2017-10-03,Ä,g,h
2017-10-04,1.0,0.000694,1.0,0.001424,0.0,0.002118,2017-10-04,Ä,g,h
2017-10-05,4.0,0.000752,6.0,0.001238,2.0,0.001991,2017-10-05,Ä,g,h
2017-10-06,3.0,0.001563,4.0,0.004873,1.0,0.006435,2017-10-06,Ä,g,h
2017-10-07,26.0,0.007465,31.0,0.020405,5.0,0.027870,2017-10-07,Ä,g,h
2017-10-08,2.0,0.001250,4.0,0.001898,2.0,0.003148,2017-10-08,Ä,g,h