In [54]:
## Import necessary modules
import os,sys
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.dates import date2num, AutoDateFormatter, AutoDateLocator, WeekdayLocator, MonthLocator, DayLocator, DateLocator, DateFormatter
from matplotlib.dates import MO, TU, WE, TH, FR, SA, SU
from matplotlib.ticker import AutoMinorLocator, AutoLocator, FormatStrFormatter, ScalarFormatter
import numpy as np
import datetime, calendar
from datetime import timedelta
import matplotlib.patches as mpatches
from itertools import tee

sys.path.append(os.path.abspath('/home/keuch/gits/keuch/code_box/pyt/spreadsheetparsing/entwuerfe/xls_testruns/'))
from ce_funclib import determine_kernzeit as dtkz
from ce_funclib import continuity_check

#%matplotlib inline
%matplotlib tk


## Import data frome pickle generated from muß ein file mit agentenstats sein
arcpth='/home/keuch/gits/keuch/code_box/pyt/spreadsheetparsing/test_stats/archiv/'

In [55]:
######## GET A LIST OF MATCHING .xls FILES FROM THE GIVEN DIRECTORY

In [56]:
def collectxlfiles(arcpath):
    xlfilelist=list()

    for xlfile in os.listdir(arcpath):
        if xlfile.startswith('CE_al'):
            xlfileabs=os.path.join(arcpath,xlfile)
            xlfilelist.append(xlfileabs)
    return sorted(xlfilelist)

xlfilelist=collectxlfiles(arcpth)
#xlfilelist
#examplefile=xlfilelist[233]

In [57]:
###### TEST FOR DATA IN FILE, SORT OUT EMPTY FILES

In [58]:
def filetoframe(exfile):
    exframe=pd.read_excel(exfile) # this is a regular pd.DataFrame
    datecell=exframe.iloc[0,1]
    sheet_datetime=pd.to_datetime(datecell,format='%d.%m %Y : %H')
    sheet_date=sheet_datetime.date()
    
    integritycheck=exframe.iloc[2,1] # files with data have "agenten" here, files with no calls have a 'nan'

    if integritycheck != 'Agenten':
        # if it's empty, keep date for filling it later
        print('Exception: ', end='')
        except_status='ex'
        
        usefulcols={0:'tstamp',1:'agent',3:'an',4:'be',22:'vl',24:'ht_float',29:'tt_float'} # map cols to decent names
        exframe=exframe.reindex(columns=sorted(usefulcols.keys()))
        exframe.rename(columns=usefulcols,inplace=True)        
        exframe=exframe[0:1] # strip text rows and the mangled sum row
        print(sheet_datetime)
        
        exframe['tstamp']=sheet_datetime
        exframe['date']=sheet_date
        exframe['agent']='platzhalter'
        exframe[['wd','ww','mm','yy']]=exframe['tstamp'].dt.strftime('%a,%W,%m,%Y').str.split(',',expand=True) # make ww,yy,mm,wd columns
        exframe['bz']=exframe['tstamp'].apply(dtkz)
        exframe['ort']=exframe['agent'].str[0] # split the identifier into useable columns
        exframe['id']='foobar' # split the identifier into useable columns
        
        # integers should be of appropriate datatype, we received them as strings
        #exframe[['vl','an','be','ww','mm','yy']]=exframe[['vl','an','be','ww','mm','yy']].astype(np.int64) #just for the beauty of it
        exframe[['ww','mm','yy']]=exframe[['ww','mm','yy']].astype(np.int64) #just for the beauty of it
        exframe.fillna(0, inplace=True) 
        return exframe,except_status
        
    else:
        except_status='reg'
        
        exframe.columns=range(0,30) # rename columns to a temporarily more readable format, fancy rename later
        usefulcols={0:'tstamp',1:'agent',3:'an',4:'be',22:'vl',24:'ht_float',29:'tt_float'} # map cols to decent names
        exframe=exframe[sorted(usefulcols.keys())] # skip cols and keep the ones we need
        exframe.rename(columns=usefulcols,inplace=True) # rename cols
        exframe=exframe[3:-1] # strip text rows and the mangled sum row
        exframe['tstamp']=pd.to_datetime(exframe['tstamp'],format=' %d.%m.%Y %H:%M ')
        exframe['date']=exframe['tstamp'].dt.date
        exframe[['wd','ww','mm','yy']]=exframe['tstamp'].dt.strftime('%a,%W,%m,%Y').str.split(',',expand=True) # make ww,yy,mm,wd columns
        exframe['bz']=exframe['tstamp'].apply(dtkz)
        
        exframe['ort']=exframe['agent'].str[0] # split the identifier into useable columns
        exframe['id']=exframe['agent'].str[-6:] # split the identifier into useable columns
        exframe['agent']=exframe['agent'].str[2:-7] # split the identifier into useable columns
        
        # integers should be of appropriate datatype, we received them as strings
        exframe[['vl','an','be','ww','mm','yy']]=exframe[['vl','an','be','ww','mm','yy']].astype(np.int64) #just for the beauty of it

        return exframe,except_status

In [59]:
framelist=list()
exceptionlist=list()
for xfile in xlfilelist:
    
    #print('file:',xfile)
    frame_from_file,except_status=filetoframe(xfile)
    #print(frame_from_file.columns)
    #print(frame_from_file['date'])
    if except_status=='ex':
        exceptionlist.append(xfile)
    framelist.append(frame_from_file)

exceptionlist

Exception: 2017-04-17 00:00:00
Exception: 2017-05-14 00:00:00

['/home/keuch/gits/keuch/code_box/pyt/spreadsheetparsing/test_stats/archiv/CE_alle_Agenten_taeglich_2017-04-17.xls',
 '/home/keuch/gits/keuch/code_box/pyt/spreadsheetparsing/test_stats/archiv/CE_alle_Agenten_taeglich_2017-05-14.xls']

In [60]:
#### produce a unified frame with all data and sort it by timstamp and agentname
bigframeii=pd.concat(framelist)

bigframeii.sort_values(['tstamp','agent'],inplace=True)
bigframeii.reset_index(drop=True,inplace=True) # there you go

In [61]:
#bigframeii
# die exklusivlogins müssen zusammengelegt werden
unify_id={'gesinst':'995887','stanzju':'878457','papkeda':'891914'}
bigframeii.loc[bigframeii['id'] == unify_id['gesinst'],'agent'] = 'gesinst'
bigframeii.loc[bigframeii['id'] == unify_id['stanzju'],'agent'] = 'stanzju'
bigframeii.loc[bigframeii['id'] == unify_id['papkeda'],'agent'] = 'papkeda'

In [62]:
### some date locator play, can conveniently be checked against a single xls file
#def check_single_day(day):
#    dayvalues=bigframeii.loc[bigframeii['date'] == day]
#    print('htsum',dayvalues['ht_float'].sum(), end=', ')
#    print('bearbeitete sum',dayvalues['be'].sum())
#check_single_day(datetime.date(2017,4,17)) # shows that days wihtout calls are in the frame, too
#check_single_day(datetime.date(2017,4,18)) # shows that days wihtout calls are in the frame, too

htsum 0.0, bearbeitete sum 0.0
htsum 190.40000236034393, bearbeitete sum 50.0

In [76]:
#### get all dates and check whether they're contiguous
datenserie_uniq=bigframeii['date'].unique().tolist()
tage_bestand=len(datenserie_uniq)
tage_start=datenserie_uniq[0]
tage_ende=datenserie_uniq[-1:]

missing_dates=continuity_check(datenserie_uniq)
if not missing_dates:
    print('no dates are missing')
else:
    print('the following dates are not within the frame:')
    print(missing_dates)

no dates are missing

In [78]:
### PARSE AGENT DATA
### What I want:
### * get a list of all agents that have worked in the period 
### * get data for each agent
### * get average of all agents as a reference
### per agent:
### ** get all calls that have lasted longer than x times the average of all agents
### ** get a plot of all calls (by timestamp)
### ** get a plot of all days (by date)
### ** get their tendencies over the weeks (? vacation dates missing and so on)

# bigframeii.tail(10)

In [65]:
# get all agents available and create frames for kern and neben
allagents_list=sorted(bigframeii['agent'].unique())
allagents_list.extend(['Hagenow','Berlin','Alle'])
standorte=bigframeii.ort.unique().tolist()

bigk=bigframeii.loc[bigframeii['bz']=='k']
bign=bigframeii.loc[bigframeii['bz']=='n']

**we can't figure out individual calls anyway, since raw data calls have been grouped by hours already  
so we can go on and group by days to figure out averages**

In [75]:
def group_and_add_average(agentname,frame,gruppierung):
    # step one: filter by agent; if agent is a location-bound group, filter by location and change agent name to group name

    if agentname == 'Hagenow':
        nur_agent=frame.loc[frame['ort']=='H'].copy()
        nur_agent['agent']='Hagenow'
        nur_agent['id']='000001'
    elif agentname == 'Berlin':
        nur_agent=frame.loc[frame['ort']=='B'].copy()
        nur_agent['agent']='Berlin'
        nur_agent['id']='000002'
    elif agentname == 'Alle':
        nur_agent=frame.loc[frame['ort'].isin(standorte)].copy()
        nur_agent['agent']='Alle'
        nur_agent['id']='000000'    
    else:
        nur_agent=frame.loc[frame['agent']==agentname]
    
    # step 2: split into kern and neben
    k=nur_agent.loc[nur_agent['bz']=='k']
    n=nur_agent.loc[nur_agent['bz']=='n']

    # step 3: group by day (instead of hour, as it is now) and add average ht,tt
    def group_and_average(agframe):
        ### ttstamp is dropped and date will be the new index; all others summed or reduced
        colfx_day={'agent':'first','an':'sum','be':'sum','vl':'sum','ht_float':'sum','tt_float':'sum','wd':'first','ww':'first', 'mm':'first','yy':'first','bz':'first','ort':'first','id':'first'}
        ### ttstamp is dropped, date is dropped and ww will be the new index; all others summed or reduced
        colfx_week={'agent':'first','an':'sum','be':'sum','vl':'sum','ht_float':'sum','tt_float':'sum','wd':'first','mm':'first','yy':'first','bz':'first','ort':'first','id':'first'}
        
        if gruppierung=='tag':
            grpd=agframe.groupby('date').agg(colfx_day)
        elif gruppierung=='woche':
            grpd=agframe.groupby('ww').agg(colfx_week)
        elif gruppierung=='nursplit':
            grpd=agframe.copy()
        
        grpd['aht']=grpd['ht_float']/grpd['be']
        grpd['att']=grpd['tt_float']/grpd['be']
        grpd['acw']=grpd['aht']-grpd['att']

        return grpd

    # step 4 get stats grouped by day and with the average column
    k_agent=group_and_average(k)
    n_agent=group_and_average(n)

    return k_agent,n_agent

In [67]:
### generate frames grouped by day and by week for every agent, put them in a dictionary
zeiten={}
print('collecting and grouping times (neben, kern) for')
#allagents_list=list(['dehnsil']) leads to division by zero...
for namen in allagents_list:
    print(namen, end=' ')

    kern_byday,neben_byday=group_and_add_average(namen,bigframeii,'tag')
    kern_byweek,neben_byweek=group_and_add_average(namen,bigframeii,'woche')
    #kern_ungruppiert,neben_ungruppiert=group_and_add_average(namen,bigframeii,'nursplit')
    
    zeiten[namen]={'k_day':kern_byday,'k_week':kern_byweek,'n_day':neben_byday,'n_week':neben_byweek}

collecting and grouping times (neben, kern) for
beckeca beckesi beckfra bretsal dehnsil diessro gesinst geyerme gorushe haenthe haustst henniju jakobir meyergu neumath papkeda pfeifpe pinnkat platzhalter pletaan plichba rabechr radtkke reismat ruschfi scholan stanzju steffci strausi tetzlva tonnroy Hagenow Berlin Alle

,tt_float,ht_float,yy,wd,ort,agent,be,vl,mm,an,bz,id,aht,att,acw
ww,,,,,,,,,,,,,,,
10,745.499602,929.532701,2017,Mon,B,Alle,236.0,0.0,3,236.0,k,000000,3.938698,3.158897,0.779801
11,605.783595,725.966405,2017,Mon,H,Alle,209.0,0.0,3,209.0,k,000000,3.473523,2.898486,0.575037
12,586.316900,681.283298,2017,Mon,B,Alle,182.0,1.0,3,183.0,k,000000,3.743315,3.221521,0.521793
13,612.099400,714.133096,2017,Mon,B,Alle,182.0,0.0,3,182.0,k,000000,3.923808,3.363184,0.560625
14,713.900299,820.900198,2017,Mon,B,Alle,230.0,0.0,4,230.0,k,000000,3.569131,3.103914,0.465217
15,615.582900,708.583001,2017,Mon,B,Alle,188.0,0.0,4,188.0,k,000000,3.769059,3.274377,0.494681
16,596.583402,679.099908,2017,Tue,H,Alle,152.0,0.0,4,152.0,k,000000,4.467763,3.924891,0.542872
17,746.433701,843.149806,2017,Mon,B,Alle,187.0,2.0,4,189.0,k,000000,4.508822,3.991624,0.517198
18,783.583099,904.049802,2017,Mon,B,Alle,246.0,1.0,5,247.0,k,000000,3.674999,3.185297,0.489702
19,849.599600,985.950101,2017,Mon,H,Alle,255.0,0.0,5,255.0,k,000000,3.866471,3.331763,0.534708
20,849.466299,998.283099,2017,Mon,B,Alle,248.0,0.0,5,248.0,k,000000,4.025335,3.425267,0.600068
21,568.966398,668.299996,2017,Mon,B,Alle,175.0,1.0,5,176.0,k,000000,3.818857,3.251237,0.567621
22,1195.066602,1351.916799,2017,Mon,B,Alle,335.0,0.0,5,335.0,k,000000,4.035573,3.567363,0.468210
23,1898.083197,2187.816600,2017,Mon,H,Alle,552.0,0.0,6,552.0,k,000000,3.963436,3.438557,0.524879
24,2711.566902,3134.733594,2017,Mon,H,Alle,837.0,0.0,6,837.0,k,000000,3.745201,3.239626,0.505575
25,2492.316600,2870.183103,2017,Mon,H,Alle,763.0,5.0,6,768.0,k,000000,3.761708,3.266470,0.495238
26,3402.899489,4155.899899,2017,Mon,H,Alle,1135.0,15.0,6,1150.0,k,000000,3.661586,2.998149,0.663436
27,3908.399799,4665.684095,2017,Mon,H,Alle,1170.0,2.0,7,1172.0,k,000000,3.987764,3.340513,0.647252
28,3798.233307,4410.884017,2017,Mon,H,Alle,1083.0,2.0,7,1085.0,k,000000,4.072838,3.507141,0.565698
29,5182.000905,6195.883115,2017,Mon,H,Alle,1714.0,1.0,7,1715.0,k,000000,3.614868,3.023338,0.591530
30,5572.732788,6424.000418,2017,Mon,B,Alle,1575.0,2.0,7,1577.0,k,000000,4.078730,3.538243,0.540487
31,6438.000497,7436.982807,2017,Mon,H,Alle,1743.0,3.0,7,1746.0,k,000000,4.266772,3.693632,0.573140
32,5972.434112,7119.633507,2017,Mon,H,Alle,1722.0,3.0,8,1725.0,k,000000,4.134514,3.468312,0.666202
33,3343.216698,3975.333006,2017,Mon,H,Alle,1030.0,2.0,8,1032.0,k,000000,3.859547,3.245841,0.613705
34,3282.349717,3889.716801,2017,Mon,H,Alle,957.0,2.0,8,959.0,k,000000,4.064490,3.429833,0.634657
35,2294.250499,2684.533589,2017,Mon,H,Alle,631.0,0.0,8,633.0,k,000000,4.254411,3.635896,0.618515
36,1641.083401,2010.682895,2017,Mon,B,Alle,475.0,0.0,9,475.0,k,000000,4.233017,3.454912,0.778104
37,2451.833599,2930.000100,2017,Mon,B,Alle,685.0,0.0,9,685.0,k,000000,4.277372,3.579319,0.698053
38,3756.883394,4447.667598,2017,Mon,H,Alle,1083.0,1.0,9,1085.0,k,000000,4.106803,3.468960,0.637843
39,5511.033410,6577.449705,2017,Mon,B,Alle,1671.0,2.0,9,1674.0,k,000000,3.936236,3.298045,0.638190
40,3679.716191,4379.716395,2017,Mon,H,Alle,1058.0,1.0,10,1061.0,k,000000,4.139619,3.477993,0.661626
41,5282.066401,6289.900101,2017,Mon,B,Alle,1525.0,1.0,10,1528.0,k,000000,4.124525,3.463650,0.660875
42,2469.383196,2968.399703,2017,Mon,H,Alle,715.0,0.0,10,715.0,k,000000,4.151608,3.453683,0.697925
43,3620.866198,4332.133107,2017,Mon,B,Alle,1043.0,0.0,10,1043.0,k,000000,4.153531,3.471588,0.681943

In [70]:
def decminutes_to_mmss(decimal):
    #print(decimal)
    tdelta=timedelta(minutes=decimal)
    sekunden=tdelta.seconds
    minuten=(sekunden % 3600) // 60
    restsekunden=str(sekunden %60).zfill(2)
    mmssstring='{}:{}'.format(minuten, restsekunden)
    return mmssstring

def maptix2labels(ticks):
    ylabelz=list()
    for tic in ticks:
        #print(tic)
        tic=abs(tic)
        sstr=decminutes_to_mmss(tic)
        ylabelz.append(sstr)
    return ylabelz

In [71]:
# colors
bgkern='#FFF7F2'
bgnebn='#F8FFF2'
aht="#21a9ff"
att="#ceecff"
aac="#c4c4c4"
zielzeit="#FF006E"
bars="#A06A00"
aav='#000C00'

In [72]:
def plotit(agent,ww_or_dd):
    f, (ax1, ax2) = plt.subplots(1, 2, sharey=False, figsize=(17,7))
    
    ### preliminary deduction from parameters
    if ww_or_dd.lower() == 'woche':
        kzeit=zeiten[agent]['k_week'].copy()
        nzeit=zeiten[agent]['n_week'].copy()
    elif ww_or_dd.lower() == 'tage':
        kzeit=zeiten[agent]['k_day'].copy()
        nzeit=zeiten[agent]['n_day'].copy()
        
    ### check empty frames
    if (kzeit.empty and nzeit.empty):
        print('ueberhaupt keine Calls')
    elif kzeit.empty:
        print('keine calls in der Kernzeit')
        kzeit=kzeit.reindex(nzeit.index).fillna(0)
    elif nzeit.empty:
        print('keine calls in der Nebenzeit')
        nzeit=nzeit.reindex(kzeit.index).fillna(0)


    kmax=(kzeit['aht'].max())+0.5
    nmax=(nzeit['aht'].max())+0.5
    commonmax=max(kmax,nmax)
    commonmin=-0.25
    
    ersterZeitpunkt=min(min(kzeit.index),min(nzeit.index))
    letzterZeitpunkt=max(kzeit.index[-1],nzeit.index[-1])
    StartStr=str(ersterZeitpunkt)
    EndeStr=str(letzterZeitpunkt)
    
    calls_zeitraum_k=kzeit['be'].sum()
    calls_zeitraum_n=nzeit['be'].sum()
    

    htmean_k=kzeit['aht'].replace(0,np.NaN).mean()
    if np.isnan(htmean_k):
        print('this is nan')
        htmean_k=0
    htmean_n=nzeit['aht'].replace(0,np.NaN).mean() # decent mean value without the zeroes jan-mar
    if np.isnan(htmean_n):
        print('this is nan')
        htmean_n=0
    av_all_k=zeiten['Alle']['k_week']['aht'].replace(0,np.NaN).mean()
    av_all_n=zeiten['Alle']['n_week']['aht'].replace(0,np.NaN).mean()

    ### plots

    ax3 = ax1.twinx()
    ax3.tick_params('y', labelsize=6, labelcolor=bars)

    ax4 = ax2.twinx()
    ax4.tick_params('y', labelsize=6, labelcolor=bars)

    kcalls=ax3.bar(kzeit.index, kzeit['be'], width=0.7, alpha=0.1, color=bars, label='calls')
    ncalls=ax4.bar(nzeit.index, nzeit['be'], width=0.7, alpha=0.1, color=bars, label='calls')

    kaht,=ax1.plot(kzeit.index,kzeit['aht'],color=aht,label="aht")
    katt,=ax1.plot(kzeit.index,kzeit['att'],color=att,label="att")
    kacw,=ax1.plot(kzeit.index,kzeit['acw'],color=aac,label="acw")
    naht,=ax2.plot(nzeit.index,nzeit['aht'],color=aht,label="aht")
    natt,=ax2.plot(nzeit.index,nzeit['att'],color=att,label="att")
    nacw,=ax2.plot(nzeit.index,nzeit['acw'],color=aac,label="acw")

    kziel=ax1.axhline(y=3.5,color=zielzeit,ls=':',alpha=0.75, label='3:30 min')
    kreal=ax1.axhline(y=htmean_k,color=aht,ls='--',alpha=0.9, label=str(decminutes_to_mmss(htmean_k)))
    kalle=ax1.axhline(y=av_all_k,color=aav,ls='-.',alpha=0.2, label=str(decminutes_to_mmss(av_all_k)))
    nziel=ax2.axhline(y=1.5,color=zielzeit,ls=':',alpha=0.75, label='1:30 min')
    nreal=ax2.axhline(y=htmean_n,color=aht,ls='--',alpha=0.9, label=str(decminutes_to_mmss(htmean_n)))
    nalle=ax2.axhline(y=av_all_n,color=aav,ls='-.',alpha=0.2, label=str(decminutes_to_mmss(av_all_n)))

    ### ax1 labels
    ax1.set_ylim(commonmin,commonmax)

    minloc=AutoMinorLocator(4)
    ax1.yaxis.set_minor_locator(minloc)
    ax1.yaxis.set_minor_formatter(ScalarFormatter()) # is the same as major formatter

    left_tix_mj=ax1.get_yticks()
    left_tix_mn=ax1.get_yticks(minor=True)
    left_lbl_mj=maptix2labels(left_tix_mj)
    left_lbl_mn=maptix2labels(left_tix_mn)

    ax1.yaxis.set_ticklabels(left_lbl_mj)
    ax1.yaxis.set_ticklabels(left_lbl_mn,minor=True,size=6)


    ### ax2 labels
    ax2.set_ylim(ax1.get_ylim())

    ax2.yaxis.set_minor_locator(minloc)
    ax2.yaxis.set_minor_formatter(ScalarFormatter()) # is the same as major formatter

    left_tix_mj=ax2.get_yticks()
    left_tix_mn=ax2.get_yticks(minor=True)
    #print('convert major tix')
    left_lbl_mj=maptix2labels(left_tix_mj)
    #print('convert major tix')
    left_lbl_mn=maptix2labels(left_tix_mn)

    ax2.yaxis.set_ticklabels(left_lbl_mj)
    ax2.yaxis.set_ticklabels(left_lbl_mn,minor=True,size=6)

    ### color adjustments, titles, legend
    ax1.set_facecolor(bgkern)
    ax2.set_facecolor(bgnebn)

    desc_k,desc_n=str(int(calls_zeitraum_k)),str(int(calls_zeitraum_n))
    ax1.set_title('Kernzeit'+' Calls gesamt: '+desc_k, size=9)
    ax2.set_title('Nebenzeit'+' Calls gesamt: '+desc_n, size=9)

    ax1.set_xlabel(ww_or_dd, size=7)
    ax2.set_xlabel(ww_or_dd, size=7)
    ax1.tick_params('x', labelsize=8)
    ax2.tick_params('x', labelsize=8)

    ax1.set_ylabel('Minuten', rotation=90)
    ax4.set_ylabel('Calls',rotation=90,color=bars)

    f.suptitle('Bearbeitungszeiten '+agent+' nach '+ww_or_dd+' ab März 2017 bis '+ww_or_dd+' '+EndeStr)

    f.legend((kaht,katt,kacw,kziel,kreal,kalle,kcalls),('handling','talk','afterwork','zielzeit','Øzeit agent','Øzeit alle','calls'),fontsize=7,ncol=2,loc='upper right',borderaxespad=2)

    
    ### Abspeichern
    heute=datetime.date.today().strftime('%Y_%m_%d')
    bild_filename=str(heute+'_'+agent+'_'+ww_or_dd+'_'+StartStr+'-'+EndeStr)
    savepath='/home/keuch/gits/keuch/code_box/pyt/spreadsheetparsing/ce_teamleitung/plots/agenten_und_standorte/'
    speichernin=os.path.join(savepath,bild_filename)
    print(speichernin)
    #f.savefig(speichernin,ext='png')
    #plt.close()

In [73]:
for person in allagents_list[1:2]:
    print(person)
    plotit(person,'Woche')

beckesi
/home/keuch/gits/keuch/code_box/pyt/spreadsheetparsing/ce_teamleitung/plots/agenten_und_standorte/2017_11_01_beckesi_Woche_10-39

In [74]:
#### isin function is pretty neat thing for filtering
#### obviously, ww is another datatype than mm, normalization required!
zeiten['gesinst']['n_day'].loc[zeiten['gesinst']['n_day']['ww'].isin([32,33,34,35,36,37,38,39,40,41])]

,tt_float,ht_float,yy,ort,wd,ww,agent,be,vl,mm,an,bz,id,aht,att,acw
date,,,,,,,,,,,,,,,,
2017-08-12,14.7834,21.6668,2017,B,Sat,32,gesinst,14.0,0.0,8,14.0,n,770628,1.547629,1.055957,0.491671
2017-08-26,3.8333,4.9833,2017,B,Sat,34,gesinst,2.0,0.0,8,2.0,n,770628,2.491650,1.916650,0.575000
2017-09-02,3.6500,4.7833,2017,B,Sat,35,gesinst,4.0,0.0,9,4.0,n,770628,1.195825,0.912500,0.283325
2017-09-08,0.1167,0.1500,2017,B,Fri,36,gesinst,1.0,0.0,9,1.0,n,770628,0.150000,0.116700,0.033300
2017-09-09,4.6833,6.7834,2017,B,Sat,36,gesinst,7.0,0.0,9,7.0,n,770628,0.969057,0.669043,0.300014
2017-09-28,4.3167,5.3167,2017,B,Thu,39,gesinst,1.0,0.0,9,1.0,n,770628,5.316700,4.316700,1.000000
2017-10-05,0.3833,0.4167,2017,B,Thu,40,gesinst,1.0,0.0,10,1.0,n,770628,0.416700,0.383300,0.033400
2017-10-14,3.8167,7.3167,2017,B,Sat,41,gesinst,6.0,0.0,10,6.0,n,770628,1.219450,0.636117,0.583333